.TH IMAP4D "1" "" "FSF"
.SH NAME
imap4d \- manual page for imap4d (GNU Mailutils)
.SH SYNOPSIS
.B imap4d
[\fIOPTION\fR...]
.SH DESCRIPTION
GNU imap4d \fB\-\-\fR the IMAP4D daemon
.SH "REPORTING BUGS"
Report bugs to <bug-mailutils@gnu.org>.
.SH "SEE ALSO"
The full documentation for
.B imap4d
is maintained as a Texinfo manual.  If the
.B info
and
.B imap4d
programs are properly installed at your site, the command
.IP
.B info imap4d
.PP
should give you access to the complete manual.
