.TH POP3D "1" "" "FSF"
.SH NAME
pop3d \- manual page for pop3d (GNU Mailutils)
.SH SYNOPSIS
.B pop3d
[\fIOPTION\fR...]
.SH DESCRIPTION
GNU pop3d \fB\-\-\fR the POP3 daemon
.SH "REPORTING BUGS"
Report bugs to <bug-mailutils@gnu.org>.
.SH "SEE ALSO"
The full documentation for
.B pop3d
is maintained as a Texinfo manual.  If the
.B info
and
.B pop3d
programs are properly installed at your site, the command
.IP
.B info pop3d
.PP
should give you access to the complete manual.
