.TH POPAUTH "1" "" "FSF" "User Commands"
.SH NAME
popauth \- manual page for popauth (GNU Mailutils)
.SH SYNOPSIS
.B popauth
[\fIOPTION\fR...]
.SH DESCRIPTION
GNU popauth \fB\-\-\fR manage POP3 authentication database
.SH "REPORTING BUGS"
Report bugs to <bug-mailutils@gnu.org>.
.SH "SEE ALSO"
The full documentation for
.B popauth
is maintained as a Texinfo manual.  If the
.B info
and
.B popauth
programs are properly installed at your site, the command
.IP
.B info popauth
.PP
should give you access to the complete manual.
